app = 'discord-esport-manager-ts'
primary_region = 'lhr'
swap_size_mb = 1024

[[mounts]]
source = 'bot_data'
destination = '/data'

[[vm]]
memory = 512
cpu_kind = 'shared'
cpus = 1

[env]
PRISMA_DATABASE_URL = 'file:/data/db.sqlite'
