app = 'discord-esport-manager-ts'
primary_region = 'lhr'
swap_size_mb = 512

[[mounts]]
source = 'bot_data'
destination = '/data'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1

[env]
DATABASE_URL = 'file:/data/db.sqlite'
